### ISSUE TITLE
parcels.convert breaks with AttributeError: module 'parcels' has no attribute 'convert'

### ISSUE THREAD

**Issue by erikvansebille** [Parcels-code/Parcels#2794]
### Parcels version

v4

### Description

Our notebook renderings fail - both on RTD as well as locally. Surprisingly, our tests all pass. It has to do with `parcels.convert`

When running `pixi run docs-clean`, I now get
```
AttributeError: module 'parcels' has no attribute 'convert'
```

Adding a line `import parcels.convert` does make the rendering of notebooks work again

No idea why this has suddenly happened. I did a git bisect and that returned a8db856d05756b41e267d86b63efbc7c656f82f5 (merging #2777) as the first breaking commit on main.

@VeckoTheGecko, could you take a look?

### Code sample

```python
import parcels
parcels.convert
```

### Error
```
AttributeError: module 'parcels' has no attribute 'convert'
```

**Comment by j-atkins** [comment]
I wonder whether it does indeed have something to do with #2777 with the `from parcels.convert...` line removed from model.py (i.e. [here](https://github.com/Parcels-code/Parcels/pull/2777/changes#diff-da4aac7f6353f5d8a031fb85a3f00be1ede103f0139a0d02a7d0cfbc92e28392L28)).

Could this previously have been keeping the `convert` module 'alive' and in-memory via a chain of: parcels/\_\_init\_\_.py imports `FieldSet` from fieldset.py -> fieldset.py imports from `parcels._core.model` -> model.py imports from `parcels.convert`?

And now that `from parcels.convert...` is removed from model.py in #2777 means it's never brought in on start up?

**Comment by VeckoTheGecko** [comment]
Yep, that's pretty much it - its to do with how direct exporting/not direct exporting works with Python submodules.

Basically
```python
import parcels.convert
parcels.convert...
```
and 

```python
import parcels
parcels.convert...
```

are not equivalent (and the latter only works if you directly export it in the `__init__` or otherwise initialize that namespace, which looks like it was being accidentally done before).

**Comment by VeckoTheGecko** [comment]
The same thing is happening with `kernels` actually - so best we explicitly export that as well

**Comment by VeckoTheGecko** [comment]
This is unintuitive behaviour that is mainly useful for monorepo layouts to avoid long import times and avoiding initializing modules that aren't being used (IIRC scipy and sklearn have used it, but I don't know if that's the case anymore since there are other mechanisms nowadays to avoid this initialization)
