### PR TITLE
Add `convert` and `kernels` to parcels.__init__

### LINKED ISSUE #2794: parcels.convert breaks with AttributeError: module 'parcels' has no attribute 'convert'
### Parcels version

v4

### Description

Our notebook renderings fail - both on RTD as well as locally. Surprisingly, our tests all pass. It has to do with `parcels.convert`

When running `pixi run docs-clean`, I now get
```
AttributeError: module 'parcels' has no attribute 'convert'
```

Adding a line `import parcels.convert` does make the rendering of notebooks work again

No idea why this has suddenly happened. I did a git bisect and that returned a8db856d05756b41e267d86b63efbc7c656f82f5 (merging #2777) as the first breaking commit on main.

@VeckoTheGecko, could you take a look?

### Code sample

```python
import parcels
parcels.convert
```

### Error
```
AttributeError: module 'parcels' has no attribute 'convert'
```

### PR DESCRIPTION
**Pull request by erikvansebille**
### Description

This PR fixes #2794 by explicitly adding the convert module to `src/parcels/__init__.py`. That fixed the issue with notebook rendering.

The question now is why `parcels.convert` did work before and why is then was suddenly broken...

### Checklist

- [X] Closes #2794 
- [X] This PR targets the correct branch (`main` for normal development, `v3-support` for v3 support)

### AI Disclosure

None

### CODE REVIEW

**Comment by VeckoTheGecko** [comment]
CI failure unrelated (due to a recent Pixi release :/ )
